//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualCounseling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Governorate_Table
    {
        public Governorate_Table()
        {
            this.Area_Table = new HashSet<Area_Table>();
            this.Case_Table = new HashSet<Case_Table>();
        }
    
        public int GovernorateID { get; set; }
        public string GovernorateArName { get; set; }
    
        public virtual ICollection<Area_Table> Area_Table { get; set; }
        public virtual ICollection<Case_Table> Case_Table { get; set; }
    }
}
