//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualCounseling.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndividualCounselingEntities : DbContext
    {
        public IndividualCounselingEntities()
            : base("name=IndividualCounselingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area_Table> Area_Table { get; set; }
        public DbSet<Case_Table> Case_Table { get; set; }
        public DbSet<Governorate_Table> Governorate_Table { get; set; }
        public DbSet<ProjectControl_Table> ProjectControl_Table { get; set; }
        public DbSet<ProjectTable> ProjectTable { get; set; }
        public DbSet<Session_Table> Session_Table { get; set; }
        public DbSet<Users_Table> Users_Table { get; set; }
    }
}
